name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet build -c Release
